apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: kube-system
data:
  kco-config: |
    ${kco_config}
  network-config: |
    apiVersion: v1
    kind: NetworkConfig
    podCIDR: ${cluster_cidr}
    networkProfile: ${tectonic_networking}
    calicoConfig:
      mtu: ${calico_mtu}
  tnc-config: |
    httpProxy: ${http_proxy}
    httpsProxy: ${https_proxy}
    noProxy: ${no_proxy}
    kubeletImageUrl: ${kubelet_image_url}
    kubeletImageTag: ${kubelet_image_tag}
    iscsiEnabled: ${iscsi_enabled}
    kubeconfigFetchCmd: ${kubeconfig_fetch_cmd}
    tectonicTorcxImageURL: ${tectonic_torcx_image_url}
    tectonicTorcxImageTag: ${tectonic_torcx_image_tag}
    bootstrapUpgradeCl: ${bootstrap_upgrade_cl}
    torcxStoreULL: ${torcx_store_url}
    torcxSkipSetup: ${torcx_skip_setup}
    nodeLabel: ${node_label}
    nodeTaintsParam: ${node_taints_param}
    clusterDNSIP: ${cluster_dns_ip}
    cloudProvider: ${cloud_provider}
    cloudProviderConfig: ${cloud_provider_config}
    debugConfig: ${debug_config}"
    clusterName: ${cluster_name}"

